// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwqpddtlklskarfxfgqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3cXBkZHRsa2xza2FyZnhmZ3F6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ0MDIyMTIsImV4cCI6MjA4OTk3ODIxMn0.Xr91Edx7hhmuW4-DgWAhCU7exuutj8-MgKPF5ZihPk8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});